### ISSUE TITLE
Initial setup with scenario 3.0

### ISSUE THREAD

**Issue by at88mph** [onedata/onedata#12]
Hello.  I need some help running the 3.0 scenario found here: http://github.com/onedata/getting-started.

1.  How do I spin up the Docker Containers using a pre-made YAML config file rather than configuring the UI each time?
2.  What is the API for downloading and uploading files?  I checked here: https://onedata.org/#/home/api/latest/onezone, but there is no reference to a plain upload/download.

Thank you.

**Comment by groundnuty** [comment]
@at88mph you need to add a more detailed question, since as far as I know it's all explained in the [getting-started](http://github.com/onedata/getting-started) readme ;)

For example for zone in scenario 3.0 you will find configuration at this [line](https://github.com/onedata/getting-started/blob/master/scenarios/3_0_oneprovider_onezone_multihost/docker-compose-onezone.yml#L40).

As for the second question, upload/download is only possible using the CMID protocol please see [this](https://onedata.org/?anchor=section/Authentication#/home/documentation/doc/advanced/cdmi.html).

**Comment by at88mph** [comment]
I should've mentioned I moved past this.  Thanks.

For anyone else, the CDMI is what is used for download/upload and is in a separate part of the documentation from the REST API.

Thanks!
