### ISSUE TITLE
What is the expected behavior of onedata when a provider fails or disappears?

### ISSUE THREAD

**Issue by deardooley** [onedata/onedata#14]
When a oneprovider instance fails, either a standalone provider or one acting as part of a cluster, how does onedata recover? What is the failure behavior of the onedata server and metadata assocated with the provider? Can a oneclient fail over to another server automatically if one goes down?

**Comment by lopiola** [comment]
Sorry it took so long, but here are the answers.

Oneprovider servers are monitored and restarted if needed by onepanel, which is registered and monitored by the underlying OS as a service. If the service keeps on failing regardless on restarts, the Oneprovider will be marked as offline (not much we can do here). We are currently working on failover within clusters - if there are several nodes still alive, they will take over the work of the failed node for until it comes back online. This feature can be expected in the next major release after 20.02 (which is due soon). 

What with offline Oneproviders? Well, users can only wait for them to be repaired and brought back to work. If there are more Oneproviders in the space, the metadata is always fully replicated, so you can use other Oneproviders. You should also make sure your file data has at least two replicas if you expect High Availability - this can be achieved using manual transfers or  automatic QoS rules (20.02). Otherwise, if the physical data is located on the offline Oneprovider, there is no way to recover it until it is online. 

Currently, Oneclient can be connected to just one Oneprovider - if it becomes offline, the Oneclient will stop working. Our roadmap for the future includes the ability of Oneclient to switch betweeen Oneproviders in the background as needed.

Closing the issue for now, let us know if you have any further questions.
